default_collection:
  outdir: data/
  datetime: 2013-01-01/2021-04-30
  # this demo contains a small section in Yosemite
  aoi_file: config/aoi/demo.json
  provider: 
    name: NSIDC

collections: 
  ASO_50M_SD:
    assets:
      - data

system:
  max_concurrent_extractions: 10
  # number of attempt downloading an asset if error/issues encountered
  max_download_attempts: 3
  log_level: DEBUG
  log_outdir: ./logs
  remove_existing_if_wrong_size: True

  # don't actually download, just print out what would be downloaded
  dry_run: False
