default_collection:
  outdir: data/
  datetime: 2003-01-01/2022-04-30
  aoi_file: config/aoi/conus-expanded.json
  provider: 
    name: EARTHDATA
    kwargs:
      provider_id: NSIDC_ECS

collections: 
  ASO_50M_SD:
    assets:
      - all
  ASO_50M_SWE:
    assets:
      - all
