default_collection:
  outdir: data/
  datetime: 1960-01-01/2022-12-31
  aoi_file: config/aoi/conus-expanded.json
  provider:
    name: EARTHDATA
    kwargs:
      provider_id: NSIDC_ECS

collections:
  NSIDC-0271:
    assets:
      - all
    datetime:
      1978-01-01/2007-12-31
  NSIDC-0321:
    assets:
      - all
    datetime:
      2000-03-05/2008-02-01
  NSIDC-0046:
    assets:
      - all
    datetime:
      1966-10-03/2021-12-31
  NSIDC-0530:
    assets:
      - all
    datetime:
      1999-01-01/2012-12-31
